### PR TITLE
Django 1.10 support

### PR DESCRIPTION
**Pull request by moggers87**
Adds support for Django 1.10 and drops support for 1.4, 1.5, and 1.6

Django 1.10 no longer supports the dotted notation in url patterns, so we now try to import the dotted string in `redirect_to_sudo`. The middleware has also been updated to work with the new style middleware (though I've not used it in a project yet)

The latest version of pytest-django has dropped support for Django 1.4, 1.5, and 1.6, so I've dropped them from the Travis test matrix (I was having issues with the pytest installed on Travis and pytest-django). I've removed all Django 1.4 compatibility code too.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Is it possible to at least maintain 1.6 support? Otherwise, I can't merge this. The main consumer of this project, Sentry, is on 1.6, and I'd rather not maintain awkward branches and two codebases.

**Comment by moggers87** [comment]
I have no idea what's going on with @coveralls right now

**Comment by moggers87** [comment]
Django 1.6 support is back in, but I've left out Python 3.2 and pypy3 tests because they wouldn't work with test coverage (Python 3.2 doesn't support `u''`). Technically they still work, so if you'd prefer running tests against those versions over test coverage reports I can do that.

**Comment by gabn88** [comment]
Would be great to see this merged :)

**Comment by QasimK** [comment]
@mattrobenolt Are we good to merge this in now?

**Comment by moggers87** [comment]
Added Django 1.11 to the test matrix too, as there's no code change required on top of 1.10 support

**Comment by gabn88** [comment]
Please merge :)

**Comment by moggers87** [comment]
@gabn88 if you don't have anything useful to add to this PR, please don't comment.

**Comment by marctc** [comment]
Could be interesting to add to the docs and README that this package is compatible with Django 1.10 and 1.11.

**Comment by moggers87** [comment]
Closing this PR as I'm no longer using this package.

https://github.com/justinmayer/django-elevate is a fork of this project that has Django 1.11 support if you need that.

**Pull request closed without merging**
